pragma Singleton
import QtQuick 2.0

Item {
    readonly property int nMinLimitPhaseType: 2
    readonly property int nMaxLimitPhaseType: 50000
    readonly property double aMinLimitPhaseType: 0
    readonly property double aMaxLimitPhaseType: 1e-5
    readonly property double cMinLimitPhaseType: 0
    readonly property double cMaxLimitPhaseType: 1
    readonly property double mMinLimitPhaseType: 1
    readonly property double kMinLimitPhaseType: 2
    readonly property double uMinLimitPhaseType: 0
    readonly property double uMaxLimitPhaseType: 1
    readonly property double vMinLimitPhaseType: 0
    readonly property double vMaxLimitPhaseType: 1
    readonly property double sMinLimitPhaseType: -1
    readonly property double sMaxLimitPhaseType: 1
    readonly property double hMinLimitPhaseType: 0
    readonly property double hMaxLimitPhaseType: 1
    readonly property double tMinLimitPhaseType: 1
    readonly property double samplingFrequencyMinLimitPhaseType: 1

    readonly property int nMinLimitPhaseTypeValidator: 2
    readonly property int nMaxLimitPhaseTypeValidator: 500000
    readonly property double aMinLimitPhaseTypeValidator: 0
    readonly property double aMaxLimitPhaseTypeValidator: 10e-10
    readonly property double cMinLimitPhaseTypeValidator: 0
    readonly property double cMaxLimitPhaseTypeValidator: 1
    readonly property double mMinLimitPhaseValidator: 1
    readonly property double kMinLimitPhaseTypeValidator: 2
    readonly property double uMinLimitPhaseTypeValidator: 0
    readonly property double uMaxLimitPhaseTypeValidator: 1
    readonly property double vMinLimitPhaseTypeValidator: 0
    readonly property double vMaxLimitPhaseTypeValidator: 1
    readonly property double sMinLimitPhaseTypeValidator: -1
    readonly property double sMaxLimitPhaseTypeValidator: 1
    readonly property double hMinLimitPhaseTypeValidator: 0
    readonly property double hMaxLimitPhaseTypeValidator: 1
    readonly property double tMinLimitPhaseTypeValidator: 1
    readonly property double samplingFrequencyMinLimitPhaseTypeValidator: 1

    readonly property int nMinLimitTimeDist: 2
    readonly property int nMaxLimitTimeDist: 50000
    readonly property double aMinLimitTimeDist: 0
    readonly property double aMaxLimitTimeDist: 1e-5
    readonly property double cMinLimitTimeDist: 0
    readonly property double cMaxLimitTimeDist: 1
    readonly property double mMinLimitTimeDist: 1
    readonly property double mMaxLimitTimeDist: 50000
    readonly property double uMinLimitTimeDist: 0
    readonly property double uMaxLimitTimeDist: 1
    readonly property double vMinLimitTimeDist: 0
    readonly property double vMaxLimitTimeDist: 1
    readonly property double sMinLimitTimeDist: -1
    readonly property double sMaxLimitTimeDist: 1
    readonly property double hMinLimitTimeDist: 0
    readonly property double hMaxLimitTimeDist: 1
    readonly property double lMinLimitTimeDist: 1e-20
    readonly property double lMaxLimitTimeDist: 1
    readonly property double tMinLimitTimeDist: 1

    readonly property int nMinLimitTimeDistValidator: 2
    readonly property int nMaxLimitTimeDistValidator: 500000
    readonly property double aMinLimitTimeDistValidator: 0
    readonly property double aMaxLimitTimeDistValidator: 1e-5
    readonly property double cMinLimitTimeDistValidator: 0
    readonly property double cMaxLimitTimeDistValidator: 1
    readonly property double mMinLimitTimeDistValidator: 1
    readonly property double mMaxLimitTimeDistValidator: 500000
    readonly property double uMinLimitTimeDistValidator: 0
    readonly property double uMaxLimitTimeDistValidator: 1
    readonly property double vMinLimitTimeDistValidator: 0
    readonly property double vMaxLimitTimeDistValidator: 1
    readonly property double sMinLimitTimeDistValidator: -1
    readonly property double sMaxLimitTimeDistValidator: 1
    readonly property double hMinLimitTimeDistValidator: 0
    readonly property double hMaxLimitTimeDistValidator: 1
    readonly property double lMinLimitTimeDistValidator: 1e-20
    readonly property double lMaxLimitTimeDistValidator: 1
    readonly property double tMinLimitTimeDistValidator: 1

    readonly property double aMinLimitWfafD: 0
    readonly property double aMaxLimitWfafD: 1e-5
    readonly property double pMinLimitWfafD: 0
    readonly property double pMaxLimitWfafD: 2
    readonly property int nMinLimitWfafD: 2
    readonly property int nMaxLimitWfafD: 50000
    readonly property int gMinLimitWfafD: 1
    readonly property double uMinLimitWfafD: 0
    readonly property double uMaxLimitWfafD: 1
    readonly property double vMinLimitWfafD: 0
    readonly property double vMaxLimitWfafD: 1
    readonly property double sMinLimitWfafD: -1
    readonly property double sMaxLimitWfafD: 1
    readonly property double hMinLimitWfafD: 0
    readonly property double hMaxLimitWfafD: 1
    readonly property double tMinLimitWfafD: 1

    readonly property double aMinLimitWfafDValidator: 0
    readonly property double aMaxLimitWfafDValidator: 1e-5
    readonly property double pMinLimitWfafDValidator: 0
    readonly property double pMaxLimitWfafDValidator: 2
    readonly property int nMinLimitWfafDValidator: 2
    readonly property int nMaxLimitWfafDValidator: 50000
    readonly property int gMinLimitWfafDValidator: 1
    readonly property double uMinLimitWfafDValidator: 0
    readonly property double uMaxLimitWfafDValidator: 1
    readonly property double vMinLimitWfafDValidator: 0
    readonly property double vMaxLimitWfafDValidator: 1
    readonly property double sMinLimitWfafDValidator: -1
    readonly property double sMaxLimitWfafDValidator: 1
    readonly property double hMinLimitWfafDValidator: 0
    readonly property double hMaxLimitWfafDValidator: 1
    readonly property double tMinLimitWfafDValidator: 1

    readonly property double aMinLimitWfafS: 0
    readonly property double aMaxLimitWfafS: 1e-5
    readonly property double pMinLimitWfafS: 0
    readonly property double pMaxLimitWfafS: 2
    readonly property int nMinLimitWfafS: 2
    readonly property int nMaxLimitWfafS: 500000
    readonly property int gMinLimitWfafS: 1
    readonly property int fMinLimitWfafS: 1
    readonly property double uMinLimitWfafS: 0
    readonly property double uMaxLimitWfafS: 1
    readonly property double vMinLimitWfafS: 0
    readonly property double vMaxLimitWfafS: 1
    readonly property double sMinLimitWfafS: -1
    readonly property double sMaxLimitWfafS: 1
    readonly property double hMinLimitWfafS: 0
    readonly property double hMaxLimitWfafS: 1
    readonly property double tMinLimitWfafS: 1

    readonly property double aMinLimitWfafSValidator: 0
    readonly property double aMaxLimitWfafSValidator: 1e-5
    readonly property double pMinLimitWfafSValidator: 0
    readonly property double pMaxLimitWfafSValidator: 2
    readonly property int nMinLimitWfafSValidator: 2
    readonly property int nMaxLimitWfafSValidator: 500000
    readonly property int gMinLimitWfafSValidator: 1
    readonly property int fMinLimitWfafSValidator: 1
    readonly property double uMinLimitWfafSValidator: 0
    readonly property double uMaxLimitWfafSValidator: 1
    readonly property double vMinLimitWfafSValidator: 0
    readonly property double vMaxLimitWfafSValidator: 1
    readonly property double sMinLimitWfafSValidator: -1
    readonly property double sMaxLimitWfafSValidator: 1
    readonly property double hMinLimitWfafSValidator: 0
    readonly property double hMaxLimitWfafSValidator: 1
    readonly property double tMinLimitWfafSValidator: 1

    readonly property double aMinLimitWfesSequential: 0
    readonly property double aMaxLimitWfesSequential: 1e-5
    readonly property double cMinLimitWfesSequential: 0
    readonly property double cMaxLimitWfesSequential: 10e-3
    readonly property int nMinLimitWfesSequential: 2
    readonly property int nMaxLimitWfesSequential: 50000
    readonly property int tExpextedMinLimitWfesSequential: 1
    readonly property double pMinLimitWfesSequential: 0
    readonly property double pMaxLimitWfesSequential: 1
    readonly property double uMinLimitWfesSequential: 0
    readonly property double uMaxLimitWfesSequential: 1
    readonly property double vMinLimitWfesSequential: 0
    readonly property double vMaxLimitWfesSequential: 1
    readonly property double sMinLimitWfesSequential: -1
    readonly property double sMaxLimitWfesSequential: 1
    readonly property double hMinLimitWfesSequential: 0
    readonly property double hMaxLimitWfesSequential: 1
    readonly property double tMinLimitWfesSequential: 1

    readonly property double aMinLimitWfesSequentialValidator: 0
    readonly property double aMaxLimitWfesSequentialValidator: 1e-5
    readonly property double cMinLimitWfesSequentialValidator: 0
    readonly property double cMaxLimitWfesSequentialValidator: 10e-3
    readonly property int nMinLimitWfesSequentialValidator: 2
    readonly property int nMaxLimitWfesSequentialValidator: 500000
    readonly property int tExpextedMinLimitWfesSequentialValidator: 1
    readonly property double pMinLimitWfesSequentialValidator: 0
    readonly property double pMaxLimitWfesSequentialValidator: 1
    readonly property double uMinLimitWfesSequentialValidator: 0
    readonly property double uMaxLimitWfesSequentialValidator: 1
    readonly property double vMinLimitWfesSequentialValidator: 0
    readonly property double vMaxLimitWfesSequentialValidator: 1
    readonly property double sMinLimitWfesSequentialValidator: -1
    readonly property double sMaxLimitWfesSequentialValidator: 1
    readonly property double hMinLimitWfesSequentialValidator: 0
    readonly property double hMaxLimitWfesSequentialValidator: 1
    readonly property double tMinLimitWfesSequentialValidator: 1

    readonly property int nMinLimitWfesSingle: 2
    readonly property int nMaxLimitWfesSingle: 50000
    readonly property double aMinLimitWfesSingle: 0
    readonly property double aMaxLimitWfesSingle: 1e-5
    readonly property double pMinLimitWfesSingle: 0
    readonly property double cMinLimitWfesSingle: 0
    readonly property double cMaxLimitWfesSingle: 10e-3
    readonly property double xMinLimitWfesSingle: 1
    readonly property double uMinLimitWfesSingle: 0
    readonly property double uMaxLimitWfesSingle: 1
    readonly property double vMinLimitWfesSingle: 0
    readonly property double vMaxLimitWfesSingle: 1
    readonly property double sMinLimitWfesSingle: -1
    readonly property double sMaxLimitWfesSingle: 1
    readonly property double hMinLimitWfesSingle: 0
    readonly property double hMaxLimitWfesSingle: 1
    readonly property double tMinLimitWfesSingle: 1

    readonly property int nMinLimitWfesSingleValidator: 2
    readonly property int nMaxLimitWfesSingleValidator: 500000
    readonly property double aMinLimitWfesSingleValidator: 0
    readonly property double aMaxLimitWfesSingleValidator: 1e-5
    readonly property double pMinLimitWfesSingleValidator: 0
    readonly property double cMinLimitWfesSingleValidator: 0
    readonly property double cMaxLimitWfesSingleValidator: 10e-3
    readonly property double xMinLimitWfesSingleValidator: 0
    readonly property double uMinLimitWfesSingleValidator: 0
    readonly property double uMaxLimitWfesSingleValidator: 1
    readonly property double vMinLimitWfesSingleValidator: 0
    readonly property double vMaxLimitWfesSingleValidator: 1
    readonly property double sMinLimitWfesSingleValidator: -1
    readonly property double sMaxLimitWfesSingleValidator: 1
    readonly property double hMinLimitWfesSingleValidator: 0
    readonly property double hMaxLimitWfesSingleValidator: 1
    readonly property double tMinLimitWfesSingleValidator: 1

    readonly property int nMinLimitWfesSweep: 2
    readonly property int nMaxLimitWfesSweep: 50000
    readonly property double aMinLimitWfesSweep: 0
    readonly property double aMaxLimitWfesSweep: 1e-5
    readonly property double lMinLimitWfesSweep: 1e-20
    readonly property double lMaxLimitWfesSweep: 1
    readonly property double cMinLimitWfesSweep: 0
    readonly property double cMaxLimitWfesSweep: 10e-3
    readonly property double pMinLimitWfesSweep: 0
    readonly property double uMinLimitWfesSweep: 0
    readonly property double uMaxLimitWfesSweep: 1
    readonly property double vMinLimitWfesSweep: 0
    readonly property double vMaxLimitWfesSweep: 1
    readonly property double sMinLimitWfesSweep: -1
    readonly property double sMaxLimitWfesSweep: 1
    readonly property double hMinLimitWfesSweep: 0
    readonly property double hMaxLimitWfesSweep: 1
    readonly property double tMinLimitWfesSweep: 1

    readonly property int nMinLimitWfesSweepValidator: 2
    readonly property int nMaxLimitWfesSweepValidator: 500000
    readonly property double aMinLimitWfesSweepValidator: 0
    readonly property double aMaxLimitWfesSweepValidator: 1e-5
    readonly property double lMinLimitWfesSweepValidator: 1e-20
    readonly property double lMaxLimitWfesSweepValidator: 1
    readonly property double cMinLimitWfesSweepValidator: 0
    readonly property double cMaxLimitWfesSweepValidator: 10e-3
    readonly property double pMinLimitWfesSweepValidator: 0
    readonly property double uMinLimitWfesSweepValidator: 0
    readonly property double uMaxLimitWfesSweepValidator: 1
    readonly property double vMinLimitWfesSweepValidator: 0
    readonly property double vMaxLimitWfesSweepValidator: 1
    readonly property double sMinLimitWfesSweepValidator: -1
    readonly property double sMaxLimitWfesSweepValidator: 1
    readonly property double hMinLimitWfesSweepValidator: 0
    readonly property double hMaxLimitWfesSweepValidator: 1
    readonly property double tMinLimitWfesSweepValidator: 1

    readonly property double aMinLimitWfesSwitching: 0
    readonly property double aMaxLimitWfesSwitching: 1e-5
    readonly property double cMinLimitWfesSwitching: 0
    readonly property double cMaxLimitWfesSwitching: 10e-3
    readonly property int nMinLimitWfesSwitching: 2
    readonly property int nMaxLimitWfesSwitching: 50000
    readonly property double pMinLimitWfesSwitching: 0
    readonly property double pMaxLimitWfesSwitching: 1
    readonly property double rMinLimitWfesSwitching: 0
    readonly property double rMaxLimitWfesSwitching: 1
    readonly property double uMinLimitWfesSwitching: 0
    readonly property double uMaxLimitWfesSwitching: 1
    readonly property double vMinLimitWfesSwitching: 0
    readonly property double vMaxLimitWfesSwitching: 1
    readonly property double sMinLimitWfesSwitching: -1
    readonly property double sMaxLimitWfesSwitching: 1
    readonly property double hMinLimitWfesSwitching: 0
    readonly property double hMaxLimitWfesSwitching: 1
    readonly property double tMinLimitWfesSwitching: 1

    readonly property double aMinLimitWfesSwitchingValidator: 0
    readonly property double aMaxLimitWfesSwitchingValidator: 1e-5
    readonly property double cMinLimitWfesSwitchingValidator: 0
    readonly property double cMaxLimitWfesSwitchingValidator: 10e-3
    readonly property int nMinLimitWfesSwitchingValidator: 2
    readonly property int nMaxLimitWfesSwitchingValidator: 50000
    readonly property double pMinLimitWfesSwitchingValidator: 0
    readonly property double pMaxLimitWfesSwitchingValidator: 1
    readonly property double rMinLimitWfesSwitchingValidator: 0
    readonly property double rMaxLimitWfesSwitchingValidator: 1
    readonly property double uMinLimitWfesSwitchingValidator: 0
    readonly property double uMaxLimitWfesSwitchingValidator: 1
    readonly property double vMinLimitWfesSwitchingValidator: 0
    readonly property double vMaxLimitWfesSwitchingValidator: 1
    readonly property double sMinLimitWfesSwitchingValidator: -1
    readonly property double sMaxLimitWfesSwitchingValidator: 1
    readonly property double hMinLimitWfesSwitchingValidator: 0
    readonly property double hMaxLimitWfesSwitchingValidator: 1
    readonly property double tMinLimitWfesSwitchingValidator: 1
}
