pragma Singleton
import QtQuick 2.0

Item {
    readonly property int nMinLimitPhaseType: 2
    readonly property int nMaxLimitPhaseType: 50000
    readonly property double aMinLimitPhaseType: 0
    readonly property double aMaxLimitPhaseType: 1e-5
    readonly property double cMinLimitPhaseType: 0
    readonly property double cMaxLimitPhaseType: 1
    readonly property double mMinLimitPhaseType: 1
    readonly property double kMinLimitPhaseType: 2
    readonly property double uMinLimitPhaseType: 0
    readonly property double uMaxLimitPhaseType: 1
    readonly property double vMinLimitPhaseType: 0
    readonly property double vMaxLimitPhaseType: 1
    readonly property double sMinLimitPhaseType: -1
    readonly property double sMaxLimitPhaseType: 1
    readonly property double hMinLimitPhaseType: 0
    readonly property double hMaxLimitPhaseType: 1
    readonly property double tMinLimitPhaseType: 1
    readonly property double samplingFrequencyMinLimitPhaseType: 1

    readonly property int nMinLimitTimeDist: 2
    readonly property int nMaxLimitTimeDist: 50000
    readonly property double aMinLimitTimeDist: 0
    readonly property double aMaxLimitTimeDist: 1e-5
    readonly property double cMinLimitTimeDist: 0
    readonly property double cMaxLimitTimeDist: 1
    readonly property double mMinLimitTimeDist: 1
    readonly property double mMaxLimitTimeDist: 50000
    readonly property double uMinLimitTimeDist: 0
    readonly property double uMaxLimitTimeDist: 1
    readonly property double vMinLimitTimeDist: 0
    readonly property double vMaxLimitTimeDist: 1
    readonly property double sMinLimitTimeDist: -1
    readonly property double sMaxLimitTimeDist: 1
    readonly property double hMinLimitTimeDist: 0
    readonly property double hMaxLimitTimeDist: 1
    readonly property double lMinLimitTimeDist: 1e-20
    readonly property double lMaxLimitTimeDist: 1
    readonly property double tMinLimitTimeDist: 1

    readonly property double aMinLimitWfafD: 0
    readonly property double aMaxLimitWfafD: 1e-5
    readonly property double pMinLimitWfafD: 0
    readonly property double pMaxLimitWfafD: 2
    readonly property int nMinLimitWfafD: 2
    readonly property int nMaxLimitWfafD: 50000
    readonly property int gMinLimitWfafD: 1
    readonly property double uMinLimitWfafD: 0
    readonly property double uMaxLimitWfafD: 1
    readonly property double vMinLimitWfafD: 0
    readonly property double vMaxLimitWfafD: 1
    readonly property double sMinLimitWfafD: -1
    readonly property double sMaxLimitWfafD: 1
    readonly property double hMinLimitWfafD: 0
    readonly property double hMaxLimitWfafD: 1
    readonly property double tMinLimitWfafD: 1

    readonly property double aMinLimitWfafS: 0
    readonly property double aMaxLimitWfafS: 1e-5
    readonly property double pMinLimitWfafS: 0
    readonly property double pMaxLimitWfafS: 2
    readonly property int nMinLimitWfafS: 2
    readonly property int nMaxLimitWfafS: 50000
    readonly property int gMinLimitWfafS: 1
    readonly property int fMinLimitWfafS: 1
    readonly property double uMinLimitWfafS: 0
    readonly property double uMaxLimitWfafS: 1
    readonly property double vMinLimitWfafS: 0
    readonly property double vMaxLimitWfafS: 1
    readonly property double sMinLimitWfafS: -1
    readonly property double sMaxLimitWfafS: 1
    readonly property double hMinLimitWfafS: 0
    readonly property double hMaxLimitWfafS: 1
    readonly property double tMinLimitWfafS: 1

    readonly property double aMinLimitWfesSequential: 0
    readonly property double aMaxLimitWfesSequential: 1e-5
    readonly property double cMinLimitWfesSequential: 0
    readonly property double cMaxLimitWfesSequential: 10e-3
    readonly property int nMinLimitWfesSequential: 2
    readonly property int nMaxLimitWfesSequential: 50000
    readonly property int tExpextedMinLimitWfesSequential: 1
    readonly property double pMinLimitWfesSequential: 0
    readonly property double pMaxLimitWfesSequential: 1
    readonly property double uMinLimitWfesSequential: 0
    readonly property double uMaxLimitWfesSequential: 1
    readonly property double vMinLimitWfesSequential: 0
    readonly property double vMaxLimitWfesSequential: 1
    readonly property double sMinLimitWfesSequential: -1
    readonly property double sMaxLimitWfesSequential: 1
    readonly property double hMinLimitWfesSequential: 0
    readonly property double hMaxLimitWfesSequential: 1
    readonly property double tMinLimitWfesSequential: 1

    readonly property int nMinLimitWfesSingle: 2
    readonly property int nMaxLimitWfesSingle: 50000
    readonly property double aMinLimitWfesSingle: 0
    readonly property double aMaxLimitWfesSingle: 1e-5
    readonly property double pMinLimitWfesSingle: 0
    readonly property double cMinLimitWfesSingle: 0
    readonly property double cMaxLimitWfesSingle: 10e-3
    readonly property double xMinLimitWfesSingle: 1
    readonly property double uMinLimitWfesSingle: 0
    readonly property double uMaxLimitWfesSingle: 1
    readonly property double vMinLimitWfesSingle: 0
    readonly property double vMaxLimitWfesSingle: 1
    readonly property double sMinLimitWfesSingle: -1
    readonly property double sMaxLimitWfesSingle: 1
    readonly property double hMinLimitWfesSingle: 0
    readonly property double hMaxLimitWfesSingle: 1
    readonly property double tMinLimitWfesSingle: 1

    readonly property int nMinLimitWfesSweep: 2
    readonly property int nMaxLimitWfesSweep: 50000
    readonly property double aMinLimitWfesSweep: 0
    readonly property double aMaxLimitWfesSweep: 1e-5
    readonly property double lMinLimitWfesSweep: 1e-20
    readonly property double lMaxLimitWfesSweep: 1
    readonly property double cMinLimitWfesSweep: 0
    readonly property double cMaxLimitWfesSweep: 10e-3
    readonly property double pMinLimitWfesSweep: 0
    readonly property double uMinLimitWfesSweep: 0
    readonly property double uMaxLimitWfesSweep: 1
    readonly property double vMinLimitWfesSweep: 0
    readonly property double vMaxLimitWfesSweep: 1
    readonly property double sMinLimitWfesSweep: -1
    readonly property double sMaxLimitWfesSweep: 1
    readonly property double hMinLimitWfesSweep: 0
    readonly property double hMaxLimitWfesSweep: 1
    readonly property double tMinLimitWfesSweep: 1

    readonly property double aMinLimitWfesSwitching: 0
    readonly property double aMaxLimitWfesSwitching: 1e-5
    readonly property double cMinLimitWfesSwitching: 0
    readonly property double cMaxLimitWfesSwitching: 10e-3
    readonly property int nMinLimitWfesSwitching: 2
    readonly property int nMaxLimitWfesSwitching: 50000
    readonly property double pMinLimitWfesSwitching: 0
    readonly property double pMaxLimitWfesSwitching: 1
    readonly property double rMinLimitWfesSwitching: 0
    readonly property double rMaxLimitWfesSwitching: 1
    readonly property double uMinLimitWfesSwitching: 0
    readonly property double uMaxLimitWfesSwitching: 1
    readonly property double vMinLimitWfesSwitching: 0
    readonly property double vMaxLimitWfesSwitching: 1
    readonly property double sMinLimitWfesSwitching: -1
    readonly property double sMaxLimitWfesSwitching: 1
    readonly property double hMinLimitWfesSwitching: 0
    readonly property double hMaxLimitWfesSwitching: 1
    readonly property double tMinLimitWfesSwitching: 1
}
